### ISSUE TITLE
This is not an issue as much as it is a plea for help

### ISSUE THREAD

**Issue by dwilzon** [chudel/oktaStuff#1]
I'm fairly new to scripting, and python - and found your script to import users using BCRYPT.  I have tried many times, but I keep getting stuck at the 401 Forbidden portion of the code.   I've recreated the API token twice with super admin access, and can not understand why it is getting stuck at that point.  

Any help you could provide would be amazing, and I hope you don't mind the ask.   Appreciate the code you wrote, wish I understood it better, but it appears to be exactly what I think I'm looking for.

Take care and thank you for your consideration.

David

**Comment by chudel** [comment]
Sure, dude - let's work the problem together.  I'd suggest getting a bit more info out of Okta's API. It likely is something very simple (and not surprised if it's a bug on my side when I de-corpifyed the code from its original source).

In the 401 check, try outputting some more details. maybe add:
```
data = res.read()
print data.decode("utf-8"))
```
(Or something like that -- i.e.: print the output from the response. It probably has some good info.

**Comment by dwilzon** [comment]
Thanks for this!

Ok, here's example output from the first line after outputting more details:

test_cgurwood5 - Forbidden Response. User not created. Is API Token correct?
{"errorCode":"E0000011","errorSummary":"Invalid token
provided","errorLink":"E0000011","errorId":"oaeF-szIhYGRKCyjmZjZcyLcw","errorCauses":[]}

I also revalidated the token I'm using against a Postman API call to make
sure it is able to call the user api.

This is how I entered it in your code:

apiAuth = 'SSWS 00dTbATSP2CcWsQdZeB1SuRU332aKJnCzrzhogIngK'

**Comment by dwilzon** [comment]
I don't have any real idea how, but I was able to get users created.  I was
trying to see if I could get any API call to not error out and return
results.  So added this right after you do a check to see if a user has a
phone number:

if (len(ext) > 1):
phone = phone + " ext. " + ext
conn = http.client.HTTPSConnection("dev-297791.okta.com")
payload = ''
headers = {
'Accept': 'application/json',
'Content-Type': 'application/json',
'Authorization': apiAuth,
}
conn.request("GET", "/api/v1/users?limit=25", payload, headers)
res = conn.getresponse()
data = res.read()
print(data.decode("utf-8"))

-------------------------------------
Then it goes into the create A JSON Payload portion of code - and
worked.... I'm scratching my head right now.

**Comment by chudel** [comment]
` ¯\_(ツ)_/¯ `

Glad it's working for you. :) Not sure that "GET" is the call to *create* users but if it worked for you, then that's good. I'm going to close the issue for now. Open a new one if you need to.  Cheers!

**Comment by dwilzon** [comment]
I don't think it was the GET as much as it was hard coding my hostname into
the code.  Did this before creating the JSON payloads in both the create
and delete files.

      conn = http.client.HTTPSConnection("dev-297791.okta.com")
      payload = ''

I did find out that my Developer system does not the TOTP flag enabled, so
I'm going to get that and see how it goes.  I appreciate you making that
code available.  Still don't have my head wrapped around it, but it will
really help me dig in and try to understand.

But thanks again, this is really helpful!

Take care!

David

**Comment by chudel** [comment]
Glad to help. FYI, you should be able to run the code with `apiHost = dev-297791.okta.com`.  Yeah, TOTP migration requires to preset the TOTP. If you don't need it, just edit around it. :-)
